### ISSUE TITLE
Menu - Master Volume and SFX slider example audio is still plex mouth sounds

### ISSUE THREAD

**Issue by IMAFIREHAZARD** [IMAFIREHAZARD/GWJ-54-Solid-Gold#208]
**Repro Steps**
1. Launch game
2. Click to settings menu
3. Adjust Master volume
4. Adjust SFX volume

**Expected Result**
Slider plays a sample game-sound

**Actual result**
Slider plays plex mouth sounds

**Comment by plexsoup** [comment]
I swapped those out day before launch.
